### ISSUE TITLE
Support searching

### ISSUE THREAD

**Issue by SignorMercurio** [fanux/sealos-site#11]
Reference: https://docusaurus.io/docs/search

**Comment by fanux** [comment]
<img width="884" alt="image" src="https://user-images.githubusercontent.com/8912557/176741537-f6a60347-2424-4bdd-bc73-7df6f1eb934e.png">

Anything else todo?

**Comment by SignorMercurio** [comment]
@fanux You can just reply this email saying that you're a maintainer of the website and you're able to insert Javascript snippet in the page.

**Comment by fanux** [comment]
<img width="421" alt="image" src="https://user-images.githubusercontent.com/8912557/176827300-b8043778-b1af-4b75-a739-6022b6866640.png">
https://www.algolia.com/products/search-and-discovery/crawler/ already add it, but how can I make sure it works?

**Comment by fanux** [comment]
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/8912557/176868280-599558cd-76ad-40c2-b258-44d178b87630.png">

Seems it works
