### ISSUE TITLE
Feature: add support of old docs V3

### ISSUE THREAD

**Issue by zzjin** [fanux/sealos-site#15]
We can add multiple docs versions to contain v3 doc files under same site.

tools:
 v3 doc files : https://github.com/labring/sealos/tree/main/docs/3.0
docusaurus versioned docs support: https://docusaurus.io/docs/versioning

![image](https://user-images.githubusercontent.com/679757/176202125-268a2da1-e9ab-4363-9b74-0cb7861ad33f.png)

**Comment by SignorMercurio** [comment]
I'm not sure whether it's a good idea to include docs for sealos v3. Maybe more discussions are needed?

**Comment by fanux** [comment]
> I'm not sure whether it's a good idea to include docs for sealos v3. Maybe more discussions are needed?

Agree, the v3 version will no longer be supported.

**Comment by zzjin** [comment]
OK, agreed, just provide refer link in case someone needed.
