### ISSUE TITLE
bug: Example error

### ISSUE THREAD

**Issue by cuisongliu** [fanux/sealos-site#16]
![image](https://user-images.githubusercontent.com/4150905/176204905-ba87a1c2-3fdb-40e0-94ba-f9e1e5f4ee24.png)

https://docs.sealos.io/docs/cli/build#dockerfile-2 

COPY manifests ./cni

**Comment by SignorMercurio** [comment]
There are 3 occurrences of `COPY manifests ./manifests` in this doc, should be replace them all?

**Comment by cuisongliu** [comment]
No, this is the only mistake.

We mainly see that the execution directory of CMD should be consistent with the directory copied to the target directory. I see that there is only something wrong with this place.
