### ISSUE TITLE
Feature: Replace index feature images

### ISSUE THREAD

**Issue by zzjin** [fanux/sealos-site#21]
as index feature images are borrowed straight from origin [Docusaurus](https://docusaurus.io/) images, we need to replace them with ours.

**Comment by ronaklalwanii** [comment]
Hi @zzjin,

I'd love to help do you have images or illustrations? 

I have some illustrations in my mind that can be used. Let me know i'll create a PR :)

**Comment by zzjin** [comment]
> 

Thanks for focus.
What we want is about three images: (just clarify, any suggestions are open!)
1. One image to show how simple `SealOS` can quickly start cloud apps on k8s with simple click.
2. One image to show vary apps can combine together in to one ecosystem, and anyone can easily add there's to join.
3. One image to show users can obtain other's already comminated cloud service using applications market.

ideas/images/illustrations PR are WELCOME!

**Comment by fanux** [comment]
@ronaklalwanii Looking forward to your illustrations~

**Comment by ronaklalwanii** [comment]
Hi @fanux,

 I apologize for the delay I was out the whole weekend.

I get it done ASAP.

**Comment by ronaklalwanii** [comment]
Hi @fanux & @zzjin,

I have created a pr for the images :)

**Comment by fanux** [comment]
@ronaklalwanii thanks for nice images~
