### ISSUE TITLE
新官网问题整理

### ISSUE THREAD

**Issue by fanux** [fanux/sealos-site#67]
1. start now 的链接改成 cloud.sealos.io

2. 
<img width="359" alt="image" src="https://user-images.githubusercontent.com/8912557/212445054-50844d4e-2a37-48f0-90ac-fc980a700769.png">
文案修改成：sealos is a Kubernetes distribution, a general-purpose cloud operating system for managing cloud-native applications.

3. 
<img width="372" alt="image" src="https://user-images.githubusercontent.com/8912557/212445121-fd9332c2-5d3f-49a0-b713-a052408de13e.png">
文案标题：sealos cloud native appstore
内容：Fully compatible with docker registry, one-click installation of various distributed cloud-native applications

4. 
<img width="380" alt="image" src="https://user-images.githubusercontent.com/8912557/212445221-3e1f34a5-7378-4c44-91c2-a9d9355f7224.png">
文案标题：sealos pgsql database
内容：One-click creation of highly available pgsql database, multi-database cluster management, backup and recovery

5. 
<img width="372" alt="image" src="https://user-images.githubusercontent.com/8912557/212445310-b25c46a8-6b4d-41c9-b846-f3856a8bcde5.png">
文案标题： sealos cloud provider
内容：Create an independent kubernetes cluster in minutes on AWS or other public clouds, and manage multiple clusters

**Comment by fanux** [comment]
6. 
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/8912557/212445442-3a6bb021-fb46-4b0b-9957-c3bfb5e9908e.png">

7.
<img width="726" alt="image" src="https://user-images.githubusercontent.com/8912557/212445500-c9c30b08-c1ba-42eb-a71e-700a68580214.png">
Build once and run everywhere （需要馨月改图）

8.
<img width="653" alt="image" src="https://user-images.githubusercontent.com/8912557/212445656-5c6e7565-2276-496c-88a2-d4072c5f85d5.png">
文案从老版本复制过来，包括其它 applications

9.
<img width="799" alt="image" src="https://user-images.githubusercontent.com/8912557/212445788-bf1a45b8-b13e-4aa7-b754-add0f6d90f91.png">
这里加个 github 图标和链接

**Comment by fanux** [comment]
10. 
<img width="216" alt="image" src="https://user-images.githubusercontent.com/8912557/212445862-a9e4ea9c-c035-4784-8e12-992066d04743.png">
可以去掉了

**Comment by fanux** [comment]
推特链接：https://twitter.com/sealosio

**Comment by fanux** [comment]
<img width="204" alt="image" src="https://user-images.githubusercontent.com/8912557/212446250-ce8eeab0-53e8-40c3-a02c-f082016b275b.png">
邮箱改成 fanux@sealos.io 电话可以去掉

<img width="176" alt="image" src="https://user-images.githubusercontent.com/8912557/212446272-bea917e0-a1d2-4e2f-b419-b7c62289a389.png">
discord 会是我们社区主战场，可以这里再加一个，甚至我和馨月讨论一下在更显眼的地方也加一下

**Comment by zzjin** [comment]
<img width="1468" alt="image" src="https://user-images.githubusercontent.com/679757/212586497-fa2e9493-57a4-4ad7-a2ca-af96699da4f6.png">
无法选择header的doc那些

**Comment by fanux** [comment]
你这是夜间模式？

**Comment by zzjin** [comment]
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/679757/212646446-4ff0840e-4e54-4b10-9a95-574833080f3a.png">
默认的字体要多几个,mac,windows,android,ios都要支持下,不然手机看起来会很奇怪的字体?

**Comment by zzjin** [comment]
<img width="613" alt="image" src="https://user-images.githubusercontent.com/679757/212646725-3662094d-9629-43f4-8323-1ac2df20434b.png">
“中”这个字没对齐

**Comment by zzjin** [comment]
<img width="906" alt="image" src="https://user-images.githubusercontent.com/679757/212683196-898feee3-542a-4f9b-9ab8-351f0a0b64fd.png">
代码样式不显示了

**Comment by zzjin** [comment]
<img width="922" alt="image" src="https://user-images.githubusercontent.com/679757/212683726-7579fca9-070c-41ba-8d3e-cfc516f4a3ed.png">
浅色模式的选中样式也不对

**Comment by fanux** [comment]
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/8912557/212691052-9dcdf296-4269-4f47-87c0-fce606238ae3.png">
细节，这里 master 不能是 4个，应该是3个或者5个，就3个吧

**Comment by zzjin** [comment]
<img width="209" alt="image" src="https://user-images.githubusercontent.com/679757/215262031-b4a9624c-64fb-4864-a68f-81e396be77c3.png">
选中之后的颜色不对
复现方法: 进入doc,切换深色模式,再回到首页,选中的颜色就不对了
是不是需要再做一套首页的深色模式的调色板?

**Comment by zzjin** [comment]
<img width="825" alt="image" src="https://user-images.githubusercontent.com/679757/215434591-e6e2c82c-2511-415b-aae0-e627194d0a2c.png">
屏幕宽度小1000之后,右上角的搜索框颜色不对

**Comment by c121914yu** [comment]
> 度小1000之后,右上角的搜索框颜

暗夜模式，这个确实麻烦，框架没有提供手动切换模式的方法。有空再探索下底层
