### ISSUE TITLE
Migrate the existing docs and support i18n

### ISSUE THREAD

**Issue by SignorMercurio** [fanux/sealos-site#9]
The docs should support both english and chinese languages. 

Currently, some of the existing docs only have English version while others only have Chinese version (see https://github.com/labring/sealos/tree/main/docs/4.0 and https://github.com/labring/sealos/discussions). To start with, these existing docs should be translated. Then we can add i18n features to show translated versions of docs.

Meanwhile, the following docs are not well-written and need to be improved:

- [config.md](https://github.com/labring/sealos/blob/main/docs/4.0/config.md)
- [reset.md](https://github.com/labring/sealos/blob/main/docs/4.0/reset.md)
- [design/rootfs.md](https://github.com/labring/sealos/blob/main/docs/4.0/design/rootfs.md)

**Comment by zzjin** [comment]
https://github.com/fanux/sealos-site/pull/22 update more need translated docs.
